# Generated by Django 4.1.4 on 2023-01-16 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('a313cf15-9320-413f-9bfb-a6563832795c'), max_length=200, unique=True),
        ),
    ]
