# Generated by Django 4.1.4 on 2023-03-15 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('3d26b956-454d-40f9-a258-a8f07aae8ac3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f19af52f-01ad-4c80-9105-6b212ae36b8e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6f8949e6-d1bb-41b1-aec9-2124b1da0e9a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('8b8e6e5b-b41a-49c9-87f6-1f6cb2c13345'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('44f576f8-38c6-45fa-8a4e-27961d8e3dc5'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9aba7f7f-4868-4c4d-98e0-b3ca71109a30'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4c9e80c0-d874-4c9d-a007-705a6f0e13ec'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f137edfa-6ec5-4ac6-bb2f-406a460e5122'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('08214a9c-0fb9-474f-9a96-ac0db8654e92'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6e9baed2-c85c-45c3-be00-ec4ed7fc5fca'), max_length=200, unique=True),
        ),
    ]
