# Generated by Django 4.1.4 on 2023-02-17 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfee',
            name='is_issued',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('944c3187-0933-4a27-900c-2f4a23709fa9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1ccdc09f-b08b-4104-92a5-9922cb47f626'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('64741ea3-c653-42f8-99fb-a0210f5fa080'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('5d9d93e3-b135-4aef-8fb1-f54f039e5df1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9a54896c-b96c-4418-807c-638c631bcbdd'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('5398704f-4f29-4f60-85cd-ce7eb8958390'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('57f972d4-e32b-415d-ab14-fe7f43d761b1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('863fdf8d-d5db-405f-825e-a4094f112ca3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('51f976fe-3e05-4142-a38a-23896c88b874'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f27e50e6-5bc6-4ae1-ad12-a3158ec4d791'), max_length=200, unique=True),
        ),
    ]
