# Generated by Django 4.1.4 on 2023-01-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
    ]
