# Generated by Django 4.1.4 on 2023-01-16 19:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payments_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('acfca9ea-61be-424d-bd3f-4790b34ea9b4'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('3055f6cf-bfa8-43c7-9e0c-eea8166d4f18'), max_length=200, unique=True),
        ),
    ]
