# Generated by Django 4.1.4 on 2023-04-17 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_users', models.IntegerField(blank=True, null=True)),
                ('s_active_users', models.IntegerField(blank=True, null=True)),
                ('s_inactive_users', models.IntegerField(blank=True, null=True)),
                ('s_members', models.IntegerField(blank=True, null=True)),
                ('s_paid_reg', models.IntegerField(blank=True, null=True)),
                ('s_loans', models.IntegerField(blank=True, null=True)),
                ('s_paid_loans', models.IntegerField(blank=True, null=True)),
                ('s_unpaid_loans', models.IntegerField(blank=True, null=True)),
                ('t_loans', models.IntegerField(blank=True, null=True)),
                ('l_this_month', models.IntegerField(blank=True, null=True)),
                ('l_last_month', models.IntegerField(blank=True, null=True)),
                ('l_this_year', models.IntegerField(blank=True, null=True)),
                ('l_last_year', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1805a0e5-9e5c-4f9f-b6bd-d462e699ca00'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('91ae0497-a31e-4cd3-85c7-c4331560db22'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9200384b-42b4-4874-be4b-7de1c6e39707'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('23ef928d-c99d-47de-9efe-777446ba5cda'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('32263fd6-4324-4943-81fa-dd00fd4661c9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b359906f-c982-4d11-8dd4-c5afb897beba'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f9675a0b-9ab2-4eaa-a110-473e567be25b'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('24c724ae-70d1-45ad-a853-bba5cf43c5d3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b5195162-014c-41f4-9fe1-1d8c792060b2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6e05683e-8e59-4f30-8c83-7ba800d1a76f'), max_length=200, unique=True),
        ),
    ]
