# Generated by Django 4.1.4 on 2023-02-17 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loanfee_is_issued_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0f825587-1f20-42c5-b059-06f659d520e2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('15636a15-71ca-4a79-b337-3d690197b9f8'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f1e77c3a-c34c-491c-9030-543462abd6bd'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cee0f2ee-4a10-4a2b-8b7e-1f4e8122ef52'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('427f8dc7-e21d-4df5-b290-c3227297e8ba'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cb9359fc-af9b-4273-a7f3-ce5a210ef677'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('71387a34-e8af-471f-8ab1-d0e6653b9f1d'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('93c2c98e-1ab4-4d0b-9497-d9dab9d77b33'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e3eed47e-86f3-482d-bd8a-2a2c3b033df8'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('5764920c-e3ec-4877-bcb0-9fc2a21735ab'), max_length=200, unique=True),
        ),
    ]
