# Generated by Django 4.1.4 on 2023-01-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_loan_deleted_by_loan_deleted_on_loan_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalshares',
            name='c_share_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_shares_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('41991463-9936-4494-8a56-7f006c97f4d4'), max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_shares_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalshares',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='payments',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('130651eb-98aa-4847-b0b9-5a633ffdda91'), max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shares',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='shares',
            name='share_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('482c1d5d-98d1-4ec8-9655-acf770ce1c2a'), max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shares',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_shares_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6b4eb8c2-c5a6-434d-99e8-c032478b45e2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d2c3728b-c063-4367-b1ac-7f49cc9e79f9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shares',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
