# Generated by Django 4.1.4 on 2023-04-17 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_counter_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='s_unpaid_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('279c0c2b-a6d8-434a-9e40-82cdfc0a3aed'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c4daa743-6e1e-41f0-8037-8417b773be8a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('643b8421-d477-4ff6-8d30-d1274591004f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('7a159b71-39dc-4e68-95fb-c0313e126ec5'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9dc6ed4a-bf03-497c-8d35-a69330f15abe'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b08952bc-85a1-4914-ad1a-415927056f44'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('012012ce-ad95-413d-b2de-3e463bbfa1b0'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('199522ff-ff64-424d-b81b-0424ece5a589'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('8c124d02-58ed-4f8f-aa1c-bb24f0960dbb'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('750e93f8-1a36-4cd7-9ab3-87a0e7d9cc49'), max_length=200, unique=True),
        ),
    ]
