# Generated by Django 4.1.4 on 2023-02-03 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('876f1b1d-ecda-45f7-b3c3-9e0cb8e09534'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('828d1d51-a179-4d2b-a63a-d4180986c34d'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c5a932db-c041-469f-ad3d-3d371c8fdf84'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('ea4fa319-21db-4b97-bb2c-7c941c23b833'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('64b6a52e-9992-41e9-9abe-252e3e60e3e3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b971f582-2dae-47e5-84df-02b3ae9aabf3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('43de5eeb-f3c0-4683-ab6b-32e6e9706d53'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='processing',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('daa04e51-7aee-4ad2-9a79-a3eed5e3a4c6'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('a448db2a-a32e-423a-b94d-5fe7f3fb8793'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9ff29977-10c2-48c5-a9e4-ec7841efc7a8'), max_length=200, unique=True),
        ),
    ]
