# Generated by Django 4.1.4 on 2023-04-18 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_counter_s_unpaid_reg_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='t_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('950947d1-7748-4d0f-8a9c-ca7df60e362d'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1e0a38a7-5f9f-441f-bada-5ee92a27e517'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('22acf9d3-586b-460c-a923-e310730d52d6'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('2611fbbe-461b-4033-b78a-cf943c6421c5'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f03610ce-7d0f-451c-af80-189f34d62a44'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1c1e18e5-4e98-41df-b880-7cb5428b605f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1762a065-86bb-4865-9957-22a17e6c8954'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('be4eec3c-52f6-482a-967e-0782a971f96a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('25869c80-4599-4fcb-9b48-17d79f18dc1a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b3f5f6a7-0704-4b3f-b291-f4b9a8759f02'), max_length=200, unique=True),
        ),
    ]
