# Generated by Django 4.1.4 on 2023-01-19 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_account_no_account_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('345d4988-8f63-4771-85e6-92439b0fa50a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('dc936db8-5d01-4d3b-80af-e209b9c29185'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4a117ec3-f184-4a67-a162-d9f88290a8a5'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cf930515-2fb3-41d7-97f9-55d6fc210cc1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d526f282-564f-4d74-969e-d1676a993912'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f4548109-abb2-423e-a4c1-3151f68ad0d3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('ef299eea-fb88-4cc0-9dfc-644f59ee73ca'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='processing',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('dc038b47-3cb4-468e-bd38-c2a53f3cee4e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('a63268c4-1994-4f7e-97d4-d403b5151d6c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4f4b63bc-68a9-4129-84d2-5df497ba4614'), max_length=200, unique=True),
        ),
    ]
