# Generated by Django 4.1.4 on 2023-01-20 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_loan_insurance_loan_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9e625be7-aaa2-4602-87c5-821186d81c32'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('66133f65-0c7d-4427-be4a-c00011ca467f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('bec1e13c-e7ce-4558-a116-d4960f657f0c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0c6714ce-d8ce-4fe4-8f9d-ee4b0b4576be'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('68fb3282-2e30-4714-98ed-0d1fe5e3d274'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('06d5bde4-7bc3-437f-bb89-7913f8724294'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('294ea182-3899-49fc-8e77-9094c2798bfe'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='processing',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c4123c77-db91-431f-bde9-f07d459e7019'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e0034066-80f1-4015-b9b5-65145641e2b6'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1b1e7e62-8bf5-4c1c-8f76-a3dbf3b9cf12'), max_length=200, unique=True),
        ),
    ]
