# Generated by Django 4.1.4 on 2023-04-18 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_counter_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_users', models.IntegerField(blank=True, null=True)),
                ('s_active_users', models.IntegerField(blank=True, null=True)),
                ('s_inactive_users', models.IntegerField(blank=True, null=True)),
                ('s_members', models.IntegerField(blank=True, null=True)),
                ('s_paid_reg', models.IntegerField(blank=True, null=True)),
                ('s_unpaid_reg', models.IntegerField(blank=True, null=True)),
                ('s_loans', models.IntegerField(blank=True, null=True)),
                ('s_paid_loans', models.IntegerField(blank=True, null=True)),
                ('s_unpaid_loans', models.IntegerField(blank=True, null=True)),
                ('t_loans', models.IntegerField(blank=True, null=True)),
                ('l_this_month', models.IntegerField(blank=True, null=True)),
                ('l_last_month', models.IntegerField(blank=True, null=True)),
                ('l_this_year', models.IntegerField(blank=True, null=True)),
                ('l_last_year', models.IntegerField(blank=True, null=True)),
                ('t_loan', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fa74467c-a321-4a0a-81f8-8c90895a407e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('01f3bfdd-7b07-4fe7-af10-230cbc899f6b'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('504b48f4-fca2-4880-9df9-206cc490f414'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e0b9f057-2b7a-4c57-8952-59bd98a4413f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('29bd59b1-0efd-440c-9662-5acc2ee8fb2c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c22cbf13-4ce3-47c1-a466-a0428a9f42bc'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fd1b5a82-1773-4773-b986-c7781f6bb3dc'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d0eda366-64ea-4cc8-8a56-65da65022d02'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f1e3cf33-7dab-4740-bf2b-b0381e8dd598'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e54823b8-ae62-4ac1-8a5f-07d24d68fb7d'), max_length=200, unique=True),
        ),
    ]
