# Generated by Django 4.1.4 on 2023-02-03 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='amount',
            new_name='savings_entrance_fee',
        ),
        migrations.AddField(
            model_name='registration',
            name='shares_application_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='shares_entrance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('8a302b86-8833-446a-896c-5181a691b486'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('2f5bf768-77ed-4d6a-ae47-adff3842b88e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6e18bae6-214a-490a-82b3-5dab77dcf4e6'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b7a3bf04-8a31-4347-a38f-88e951718978'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c8e49280-2824-4a83-9b60-ed0c85eb1f85'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1ace2f9e-b635-4f2b-8648-5c8bbedaeab0'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('19f2e674-3ff2-4a77-acc2-8e3d20546f48'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='processing',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('45f78fdf-fd09-4694-858c-0c7957ce3430'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('64b71948-4682-4c6f-95b3-dddc5840d625'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('2d564680-e237-4f5b-95e5-2684ce750c04'), max_length=200, unique=True),
        ),
    ]
