# Generated by Django 4.1.4 on 2023-04-18 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_counter_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('2d41a7b7-0cc3-4c1e-8d4e-2aba620ba410'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1f1c2522-89d6-4fde-b8d9-32b48cb08635'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('54910ce4-f42e-4c01-b56e-7ae5d440d535'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('8285c194-5f1f-4d94-a35c-4963de6e687e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('af98b28c-7437-4546-adee-5d6df5caf2e3'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f090f762-8f75-4410-b7c5-e87cb5a1ac1f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('7d9de8b0-d704-4800-9f89-75d5e964d7fe'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('522799ef-db15-4a68-ab75-528499823795'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c5ffb495-3569-4502-9a0d-64834e933786'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('39658f6a-11b1-4853-9c8b-72d9ffbdaeda'), max_length=200, unique=True),
        ),
    ]
