# Generated by Django 4.1.4 on 2023-04-22 20:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fines',
            name='fine_no',
            field=models.CharField(default=datetime.datetime(2023, 4, 22, 20, 22, 0, 492952, tzinfo=datetime.timezone.utc), max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fines',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('3b13cd3d-8eaf-4441-97b0-e57f36f214c9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1d6e12ad-e59c-49ac-aa53-950c80530f08'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('5e18fe00-68c1-49dc-be66-e6de0b955b0d'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('01a78e91-a803-4d16-8cc7-186ca1d1a8ef'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('7afca3e4-770a-41bd-bb8d-e4d226f27bed'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e113eea6-9f13-475d-b226-5ac33862f010'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('1f5e776c-a4e3-4fc7-96df-5a6524d2adc5'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cc0d8ce5-39f9-4045-ab60-bcb92dadab73'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6009d262-e474-4ed4-8e05-cc44817010a2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('56259e34-b76e-4719-ac72-ad0740461035'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0008b4f8-98f1-4534-aa80-5374838ea981'), max_length=200, unique=True),
        ),
    ]
