# Generated by Django 4.1.4 on 2023-02-17 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_fees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_loan_fee', to='api.loanfee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6891783d-d211-416c-b580-0ccdb14653af'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('59aaf28a-cd9e-4de2-b30a-22a52332851e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6835c9cd-eb38-4699-885d-056fad7526f9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('bdd0ccd1-7d48-4f38-b05e-f4e8b2c1bfd0'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d38c0cec-cadc-46d5-97d5-2ce79021c1bd'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c644d2d1-fd85-44ec-b78a-977b7f76344b'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c94c853d-0692-4f49-a33c-d386ef6160dc'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b3852a1e-c326-47c2-88cb-cf231355ab9b'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('80bf70ef-7f34-4d77-9259-3917176c737a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('324d1472-245d-4db4-abc9-2fe6b1af7f4a'), max_length=200, unique=True),
        ),
    ]
