# Generated by Django 4.1.4 on 2023-11-04 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0012_fines_is_paid_alter_account_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("55990872-fd2c-44a6-98f1-13af9df1a788"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="capitalshares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("f203face-3e36-4a47-bda6-e724319e49b5"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("d81014fe-64ee-41d5-b5b4-0059ab5e086d"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="fines",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("26343253-01be-4157-9bcf-2a81c5bb450b"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("c82d0662-26ab-4cce-8fa2-b9c815d15b41"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanfee",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("39f933ce-d3b9-45df-bdd9-7862b08b7b3f"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="nhif",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("f33bcad9-ec05-47ab-b51e-cc28f58c9e97"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="passbook",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("cad0701f-2e20-4f7d-b09b-fc504accfa0d"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("97d9fdd6-8e86-4ab3-b5dc-522c3f5ead0d"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("05f3065e-f4ff-4c9f-b684-0977fd072c30"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("f7fb8a31-b456-4661-97c7-94eb7a630704"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transanction_id", models.CharField(max_length=200, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "money_in",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "money_out",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_statement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
