# Generated by Django 4.1.4 on 2023-02-18 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_loan_loan_fees_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e7bc83f7-6f2a-4bab-99f6-807647de8cdf'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0886e692-709c-4e87-a41c-41f7251e3120'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c6748bd9-c1fa-432f-b29a-49d436a76421'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('986e59a7-e68b-4c7f-bfd7-a2fba16f244c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('15f311e9-7c44-48c4-bfc1-061e2ab01c8d'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6ed4836b-8807-4540-939b-9173130e27fa'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fbb6aa39-5c24-4a08-8c4e-c5b6a92939b2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('5b4e601a-f0d6-4554-8903-feb146329379'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e1cfff1b-7e88-4e2e-a7e7-3f37b12d368b'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('c449338a-7025-435b-bdad-688fda958471'), max_length=200, unique=True),
        ),
    ]
