# Generated by Django 4.1.4 on 2023-02-18 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_loan_member_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_fee',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='processing_fee',
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fde72855-1324-49a6-9672-f0edde687072'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('ef9d5bff-90e4-4b3b-9eb9-24ddc6112565'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f0b19f93-fcf2-4c63-a4e3-72e758a9184f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b57463b6-b2e0-4ea2-999d-c1108281b0f8'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cabffbfe-be80-4b6a-8456-a755b70a130f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4be3ba62-eb7c-46eb-ae86-0492e6239c4c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b497bbc3-00e3-4089-a2d4-45495b988d04'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4f973e55-1bea-46e7-b5b3-86a247b7be49'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9d1d3352-eb82-4a2b-abcf-4a578af976f1'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('26b18641-95fb-46de-8892-1def98a359e6'), max_length=200, unique=True),
        ),
    ]
