# Generated by Django 4.1.4 on 2023-11-04 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0013_alter_account_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("c748f39f-818b-4148-aee8-ecb2f1714fc0"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="capitalshares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("db421f22-7922-4538-b257-5a4294bd0a64"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("64426abb-46cb-4328-84f3-7351942b8f6c"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="fines",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("b0f90746-cf50-4d4e-8c3b-63bb91523b7f"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("2ae444a9-4799-4db3-a9ef-19a84d4dff4a"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanfee",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("7e863804-2604-4533-a3b2-d0c0c6236c30"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="nhif",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("0b9eb903-9ecc-4f6d-9141-5da4dac5f31b"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="passbook",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("1b6c23bf-8cb0-476c-b324-b24bc0ee3ef8"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("93457c12-66df-4fc4-b008-f006f33d5372"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("2e77f64a-4fd0-41b4-b11e-1ec0926981af"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("614c251d-b8de-40d5-badd-a88caaf01fdc"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Withdrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_no", models.CharField(max_length=200, unique=True)),
                (
                    "transaction_id",
                    models.CharField(
                        default=uuid.UUID("5877a85c-e954-4116-90c3-8cd93caeb781"),
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_deleted", models.BooleanField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(null=True)),
                ("deleted_on", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_withdrawal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
