# Generated by Django 4.1.4 on 2023-02-18 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_loan_loan_fee_remove_loan_processing_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('6062f283-a77e-43d3-95c0-53dd8d7d1068'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('edd10d06-503f-4dd0-9b3c-a6b670f353f2'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('18774b23-e849-4618-8f0e-7b3f961fd181'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('595eb857-1f6a-4243-91ab-2e6548c67797'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('4eab7e33-4a6f-48d6-a318-3be361d12263'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('e81ed9df-3d11-4deb-9546-42079ad19369'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d557208b-ab8d-49ad-a721-e82500ddf5d9'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('f7e1d89b-c975-421e-a345-4ec27455ba8a'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d7eb0bff-eb30-4cdd-90b4-0f765874df89'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('59f65790-d46d-4e36-969e-09719bb0e83e'), max_length=200, unique=True),
        ),
    ]
