# Generated by Django 4.1.4 on 2023-02-18 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_loan_fines_alter_account_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('855656b2-cdb1-46b3-8a7c-b5eb212a1527'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitalshares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cd21f279-6964-447a-b8b2-971149ed2842'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('41cf968a-2ec1-4ae7-851b-4f9f3b20eef8'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b10ad144-15ad-4a6f-a3f4-d1e788e30194'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0a86e7cd-f32b-4cee-aa39-a9dcd940e3e4'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('9dc0eefd-a947-4030-ade4-904a91b75e95'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('002ea1d8-6c1c-46ff-8ffb-f41535c605d6'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('94e83f65-b10b-40f4-b786-a17e6d22d79c'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fd32463c-1d74-4f58-afa4-53f7c778e66e'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fb6c6513-068f-41b7-a284-27cca6de5f21'), max_length=200, unique=True),
        ),
    ]
