# Generated by Django 4.1.4 on 2023-11-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_alter_account_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("49be05d3-863b-46de-a325-74dcfb647487"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="capitalshares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("e4e3cbed-4b83-4a1c-9533-edf1d13d33e9"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("18b20431-ca35-4483-9187-7a65f5084192"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="fines",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("29cab917-f69f-4ec9-9a28-36d6f6924c2e"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("e3c5a879-b556-4a70-9627-dd100a32a72d"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanfee",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("9ef89c04-d193-4bc8-8cb3-45f1a6e51835"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="nhif",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("1744eae9-7cab-48b8-89bc-7f8033ec50ad"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="passbook",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("5042bb65-3ac3-42f0-93fd-db6968a3f909"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("549bccec-586b-4440-9ce9-cd7d8c02c17b"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("f0f548c7-8243-4c38-856e-09f6c586156f"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shares",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("a32d1c62-64c9-4df1-84c4-ef1aa858e8f6"),
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_statement",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawl",
            name="transaction_id",
            field=models.CharField(
                default=uuid.UUID("5a201695-3709-4d35-9630-6ea1239f2530"),
                max_length=200,
                unique=True,
            ),
        ),
    ]
